### ISSUE TITLE
Toin0u\Geotools\Geotools::point() not found after composer update

### ISSUE THREAD

**Issue by goranata** [toin0u/Geotools-laravel#10]
Hi, 

I just made composer update, and I got the following error.

FatalErrorException in Facade.php line 213:
Call to undefined method Toin0u\Geotools\Geotools::point()

Upon commenting the $point part, everything seems to be working properly.

**/_$point    =  Geotools::point()->setFrom($coordA)->setTo($coordB);
$compassDir = $point->finalCardinal();_/**

**Comment by goranata** [comment]
Actually I found in the detailed description for POINTS;

$point = Geotools::**vertex()**->setFrom($coordA)->setTo($coordB);
$compassDir = $point->finalCardinal();

**Comment by toin0u** [comment]
Yes it's exactly that :) See the release here https://github.com/thephpleague/geotools/releases/tag/0.7.0
You can also use the version 0.6.0 otherwise!
