### ISSUE TITLE
Function for Radius + Longitude & Latitude

### ISSUE THREAD

**Issue by keithyeohh** [toin0u/Geotools-laravel#6]
Hey toin0u,

Wanted to ask if I have the longitude and latitude, and I wanted to get all the longitude and latitude for radius within 5km, may I know which function can I apply?

My scenario is, the database is storing user's latitude & longitude and I wanted to get the all the nearby users.

Looking forward to your reply :)

**Comment by toin0u** [comment]
Hi @keithyeohh 

Someone asked me the same question in IRC :)

1. Create a `Coordinate` object with the original latitude & longitude.
2. You need to fetch user's latitude & longitude and to make a collection of `Coordinate`.
3. Then you can iterate over the collection and calculate the distance which should be under 5km.

This can work but can be very very slow... But in some context, that's is fine :)

I think I'll use (if possible) MongoDB with its geospacial indexes and queries or PostgreSQL with its basic feature / PostGIS ..

**Comment by toin0u** [comment]
Hoped my answer helped you a bit :) I close this, feel free to reopen if needed.
