### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by fernandovinta** [toin0u/Geotools-laravel#7]
Do you plan to make this package compatible with Laravel 5?

**Comment by toin0u** [comment]
Sure! But you're welcome to make a PR :)

**Comment by goranata** [comment]
Hello, just to ask, when can we expect the package for L5 approx. ?

**Comment by toin0u** [comment]
Well, no so much time atm :-/ But it should be done as I can see a lot of people is asking for it :)

**Comment by toin0u** [comment]
@fernandovinta @goranata I've made the `laravel5.x` branch here https://github.com/toin0u/Geotools-laravel/tree/laravel5.x

Can you test it by requiring `"toin0u/geotools-laravel": "dev-laravel5.x@dev"` in your Laravel 5 project  please ? If it's working as expected then I'll merge into master and release a new version. I'm waiting for your feedbacks :)

**Comment by goranata** [comment]
![l4-composer](https://cloud.githubusercontent.com/assets/6684817/6320699/855567aa-bae5-11e4-89c4-1495452583e7.jpg)

Wow this was super quick. Looks like it works :)

Tested only with the Distance example code, the results are the same as the commented.

**Comment by toin0u** [comment]
Thank you @goranata :)

**Comment by goranata** [comment]
Any time, thank you @toin0u  as well :)

**Comment by toin0u** [comment]
@goranata let's wait @fernandovinta's feedback as well before merging it to master :)

**Comment by goranata** [comment]
Yes off course, there is no need to rush :)

**Comment by fernandovinta** [comment]
Thank you @toin0u, worked perfectly in my project. I guess it is ready to master branch.

![captura de tela 2015-02-23 as 09 29 12](https://cloud.githubusercontent.com/assets/1881118/6327774/8d3a3690-bb3e-11e4-9c7d-03a16d0d206c.png)

**Comment by toin0u** [comment]
@fernandovinta Thank you for your report! I'll merge this asap :)

**Comment by toin0u** [comment]
@fernandovinta @goranata what do you think if I tag `1.0.0` ?

**Comment by fernandovinta** [comment]
@toin0u I think it is a good idea :)

**Comment by toin0u** [comment]
@fernandovinta @goranata so it's tagged `1.0.0` and thank you both of you! https://github.com/toin0u/Geotools-laravel/releases/tag/1.0.0

**Comment by goranata** [comment]
Excellent :)

**Comment by RomainSauvaire** [comment]
Well done Antoine (bien joué) !

**Comment by toin0u** [comment]
@goranata @RomainSauvaire Thanks :)

**Comment by RomainSauvaire** [comment]
You really need need Illuminate/Support ~4.0 to install Geotools ? What about the ~5.0 tag ? I feel lame using a previous version ;)

![image](https://cloud.githubusercontent.com/assets/1195119/6329071/852f2d96-bb6d-11e4-8bea-e2bab737fb2e.png)

**Comment by toin0u** [comment]
No it's not needed :)

![](https://i.imgur.com/4bg95Lf.png)
